
// React
import { FC } from 'react';
// Next
import Head from "next/head";
// Modules Components
import { CrmStartupLandingPage } from "modules/crm/startup/components/landing-page";

const StartupCrm: FC = () => {
    return (
        <>
            <Head>
                <title>CRM for Startups | Attio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CrmStartupLandingPage />
        </>
    );
}

export default StartupCrm;